### PR TITLE
Git week1

### PR DESCRIPTION
**Pull request by Impressiv3**
Created my_favorite_food.txt and updated its content.
Created my_second_favorite_food.txt and updated its content.
Created countries.txt  and updated its content.

### CODE REVIEW

**Review by martamatos — CHANGES_REQUESTED** [review]
Very good Bálint! :D

One final task for you: can you add another countries to the countries.txt file, commit and push please?
This is to mimic the process of implementing feedback :)

**Comment by Infamou5** [comment]
Have updated the file with more countries.

**Review by martamatos — APPROVED** [review]
Very good! Now you can merge your PR (and remember to delete the branch as well, since you will not use it again :))

**Comment by Infamou5** [comment]
Merge confirmed by **martamatos.**

**Pull request merged**
