### PR TITLE
Javascript javascript3 week1

### PR DESCRIPTION
**Pull request by Impressiv3**

### CODE REVIEW

**Comment by Infamou5** [comment]
Ready for review.

**Review by flom84 — COMMENTED** [review]
- Giphy app doesn't work when you load the `index.html` with LiveServer (visual studio code plugin)
image
 - Weather app shows undefined when I have selected a city.
image

**Comment by Infamou5** [comment]
The reason why it doesn't want to work for you is this =>  url = `https://api.giphy.com/v1/gifs/search?api_key=REMOVEDBYUSER&q=${searchValue}&limit=${counterValue}&offset=0&rating=g&lang=en`;
REMOVEDBYUSER - I have removed my API key for obvious reasons. I have tested it before I made a pull request.
I use GitGuardian that won't allow me to post not Public API keys on Github.

**Comment by Infamou5** [comment]
The same goes for the WEATHER APP:
function cityWeatherHandler() {
  url = `http://api.openweathermap.org/data/2.5/weather?q=${selectedCity}&units=metric&APPID=REMOVEDBYUSER`;
  displayWeather(url);
}

REMOVEDBYUSER - API key has been removed for obvious reasons.

**Review by flom84 — APPROVED** [review]

**Pull request merged**
